name: Modal Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal

      - name: Gather environment variables and secrets
        env:
          MY_SECRET_ENCODED_64: ${{ secrets.SSH_KEY_ENCODED }}
        run: |
          mkdir .secrets
          echo $SSH_KEY_ENCODED | base64 --decode > .ssh/id_rsa.pub

      - name: Deploy job
        run: |
          modal deploy run.py